### ISSUE TITLE
作者去哪儿了？

### ISSUE THREAD

**Issue by angangi** [silence940109/Java#7]
github账号和csdn好久没更新了，是转行了吗？

**Comment by scalad** [comment]
> github账号和csdn好久没更新了，是转行了吗？
还健在

**Comment by scalad** [comment]
> github账号和csdn好久没更新了，是转行了吗？

还健在

**Comment by GaoMinzhu** [comment]
啥？ 没有啊



gmz.sdlk@foxmail.com
 
发件人： 王培坤
发送时间： 2020-05-10 20:26
收件人： scalad/Note
抄送： Subscribed
主题： Re: [scalad/Note] 作者去哪儿了？ (#7)
github账号和csdn好久没更新了，是转行了吗？
还健在
